### ISSUE TITLE
Segmentation error (on training)

### ISSUE THREAD

**Issue by zsxacdvbbnm16** [uzh-rpg/rl_vo#2]

**Comment by XinyiChu** [comment]
do u meet a error like this ?:
Traceback (most recent call last):
File "/workspace/vo_rl/env/svo_wrapper.py", line 85, in get_images_pose
batch = next(self.dataloader_iter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "train.py", line 104, in main
model.learn(
File "/workspace/vo_rl/rl_algorithms/ppo.py", line 347, in learn
return super().learn(
File "/workspace/vo_rl/rl_algorithms/on_policy_algorithm.py", line 274, in learn
total_timesteps, callback = self._setup_learn(
File "/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 423, in _setup_learn
self._last_obs = self.env.reset() # type: ignore[assignment]
File "/workspace/vo_rl/env/svo_wrapper.py", line 213, in reset
images, gt_poses, new_seq = self.get_images_pose()
File "/workspace/vo_rl/env/svo_wrapper.py", line 89, in get_images_pose
batch = next(self.dataloader_iter)
StopIteration

**Comment by Yuxuan222** [comment]
me too, meet the problem like "Segmentation fault (core dumped)" (using docker)

**Comment by kmax2001** [comment]
In my case, tartanair_tools download image files as ".png". However, the tartan_loader reads image as ".jpg" format
