### ISSUE TITLE
StopIteration Error

### ISSUE THREAD

**Issue by XinyiChu** [uzh-rpg/rl_vo#3]
When I run python train.py . It shows:
 Traceback (most recent call last):
  File "/workspace/vo_rl/env/svo_wrapper.py", line 85, in get_images_pose
    batch = next(self.dataloader_iter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 104, in main
    model.learn(
  File "/workspace/vo_rl/rl_algorithms/ppo.py", line 347, in learn
    return super().learn(
  File "/workspace/vo_rl/rl_algorithms/on_policy_algorithm.py", line 274, in learn
    total_timesteps, callback = self._setup_learn(
  File "/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 423, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "/workspace/vo_rl/env/svo_wrapper.py", line 213, in reset
    images, gt_poses, new_seq = self.get_images_pose()
  File "/workspace/vo_rl/env/svo_wrapper.py", line 89, in get_images_pose
    batch = next(self.dataloader_iter)
StopIteration
what's wrong with that

**Comment by sujit-168** [comment]
same error i meet, , do you have any solution?

**Comment by sujit-168** [comment]
> same error i meet, , do you have any solution?


By adding debug information, located the problem in func
https://github.com/uzh-rpg/rl_vo/blob/5e36e421efeaac9ece88b1823022698fbc92b72d/dataloader/tartan_loader.py#L132

need to notice code line as follows
- https://github.com/uzh-rpg/rl_vo/blob/5e36e421efeaac9ece88b1823022698fbc92b72d/dataloader/tartan_loader.py#L136

- https://github.com/uzh-rpg/rl_vo/blob/5e36e421efeaac9ece88b1823022698fbc92b72d/dataloader/tartan_loader.py#L150

- https://github.com/uzh-rpg/rl_vo/blob/5e36e421efeaac9ece88b1823022698fbc92b72d/dataloader/tartan_loader.py#L153

**Comment by XinyiChu** [comment]
> > same error i meet, , do you have any solution?
> 
> By adding debug information, located the problem in func
> 
> https://github.com/uzh-rpg/rl_vo/blob/5e36e421efeaac9ece88b1823022698fbc92b72d/dataloader/tartan_loader.py#L132
> 
> need to notice code line as follows
> 
> * https://github.com/uzh-rpg/rl_vo/blob/5e36e421efeaac9ece88b1823022698fbc92b72d/dataloader/tartan_loader.py#L136
> * https://github.com/uzh-rpg/rl_vo/blob/5e36e421efeaac9ece88b1823022698fbc92b72d/dataloader/tartan_loader.py#L150
> * https://github.com/uzh-rpg/rl_vo/blob/5e36e421efeaac9ece88b1823022698fbc92b72d/dataloader/tartan_loader.py#L153
